import { StylePreset } from '../types';

export const DEFAULT_STYLE_PRESETS: StylePreset[] = [
  {
    id: 'classic-anime',
    name: 'Classic Anime (Makoto)',
    nameHi: 'क्लासिक एनिमे (मकॉतो स्टाइल)',
    category: 'anime',
    description: 'Crisp black ink outlines, stepped vibrant cel shading, and subtle sky bloom.',
    descriptionHi: 'तेज ब्लैक इंक आउटलाइन्स, वाइब्रेंट सेल-शेडिंग और खूबसूरत एनिमे ग्लो।',
    accentColor: '#3b82f6',
    previewGradient: 'from-blue-600 via-indigo-600 to-sky-400',
    parameters: {
      edgeThreshold: 45,
      edgeThickness: 2,
      edgeDarkness: 85,
      colorBands: 6,
      smoothing: 5,
      saturation: 135,
      contrast: 125,
      brightness: 5,
      bloomGlow: 30,
      halftoneDotSize: 0,
      pixelBlockSize: 1,
      sketchHatch: 0,
      paperGrain: 5,
      fpsThrottle: 24,
      colorTint: 'none',
    },
  },
  {
    id: 'ghibli-watercolor',
    name: 'Studio Ghibli Painting',
    nameHi: 'स्टूडियो घिबली पेंटिंग',
    category: 'anime',
    description: 'Soft painterly brush strokes, lush vibrant foliage tones, gentle watercolor paper grain.',
    descriptionHi: 'सॉफ्ट पेंटरली ब्रश स्ट्रोक्स, वाटरकलर ब्लेंडिंग और खूबसूरत नेचर कलर्स।',
    accentColor: '#10b981',
    previewGradient: 'from-emerald-600 via-teal-600 to-amber-300',
    parameters: {
      edgeThreshold: 35,
      edgeThickness: 1,
      edgeDarkness: 65,
      colorBands: 7,
      smoothing: 8,
      saturation: 145,
      contrast: 110,
      brightness: 10,
      bloomGlow: 40,
      halftoneDotSize: 0,
      pixelBlockSize: 1,
      sketchHatch: 0,
      paperGrain: 18,
      fpsThrottle: 0,
      colorTint: 'none',
    },
  },
  {
    id: 'comic-pop-art',
    name: 'Spider-Verse Comic',
    nameHi: 'कॉमिक बुक पॉप-आर्ट',
    category: 'comic',
    description: 'Bold retro halftone dots, heavy comic ink lines, punchy four-color printing.',
    descriptionHi: 'बोल्ड हाफटोन डॉट्स, डार्क कॉमिक आउटलाइन और पंची 4-कलर प्रिंटिंग।',
    accentColor: '#ef4444',
    previewGradient: 'from-red-600 via-yellow-500 to-pink-600',
    parameters: {
      edgeThreshold: 55,
      edgeThickness: 3,
      edgeDarkness: 95,
      colorBands: 4,
      smoothing: 4,
      saturation: 160,
      contrast: 140,
      brightness: 0,
      bloomGlow: 10,
      halftoneDotSize: 6,
      pixelBlockSize: 1,
      sketchHatch: 0,
      paperGrain: 12,
      fpsThrottle: 12,
      colorTint: 'none',
    },
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon Glow',
    nameHi: 'साइबरपंक नियॉन ग्लो',
    category: 'cyber',
    description: 'Dark high-contrast matrix, glowing electric cyan and magenta contour wires.',
    descriptionHi: 'डार्क बैकग्राउंड, चमकती हुई नियॉन आउटलाइन्स और इलेक्ट्रिक वाइब्स।',
    accentColor: '#06b6d4',
    previewGradient: 'from-cyan-500 via-fuchsia-600 to-purple-900',
    parameters: {
      edgeThreshold: 40,
      edgeThickness: 2,
      edgeDarkness: 90,
      colorBands: 5,
      smoothing: 3,
      saturation: 175,
      contrast: 155,
      brightness: -10,
      bloomGlow: 75,
      halftoneDotSize: 0,
      pixelBlockSize: 1,
      sketchHatch: 0,
      paperGrain: 0,
      fpsThrottle: 0,
      colorTint: '#06b6d4',
      invertEdges: true,
    },
  },
  {
    id: 'retro-8bit',
    name: 'Retro 8-Bit Pixel Game',
    nameHi: 'रेट्रो 8-बिट पिक्सल गेम',
    category: 'retro',
    description: 'Nostalgic arcade pixelation mosaic with restricted color gamut and crisp grid.',
    descriptionHi: 'नॉस्टैल्जिक आर्केड पिक्सलेशन, विंटेज गेमिंग कलर्स और रेट्रो चार्म।',
    accentColor: '#8b5cf6',
    previewGradient: 'from-purple-700 via-pink-600 to-amber-500',
    parameters: {
      edgeThreshold: 30,
      edgeThickness: 1,
      edgeDarkness: 70,
      colorBands: 4,
      smoothing: 2,
      saturation: 130,
      contrast: 130,
      brightness: 0,
      bloomGlow: 0,
      halftoneDotSize: 0,
      pixelBlockSize: 8,
      sketchHatch: 0,
      paperGrain: 0,
      fpsThrottle: 15,
      colorTint: 'none',
    },
  },
  {
    id: 'pencil-sketch',
    name: 'Pencil & Charcoal Sketch',
    nameHi: 'पेंसिल और चारकोल स्केच',
    category: 'art',
    description: 'Hand-drawn graphite look with cross-hatching textures and rough graphite edges.',
    descriptionHi: 'हाथ से बना ग्रैफाइट स्केच, क्रॉस-हैचिंग और चारकोल पेपर टेक्सचर।',
    accentColor: '#71717a',
    previewGradient: 'from-zinc-400 via-zinc-600 to-zinc-800',
    parameters: {
      edgeThreshold: 60,
      edgeThickness: 2,
      edgeDarkness: 90,
      colorBands: 3,
      smoothing: 3,
      saturation: 0, // black and white
      contrast: 145,
      brightness: 15,
      bloomGlow: 0,
      halftoneDotSize: 0,
      pixelBlockSize: 1,
      sketchHatch: 60,
      paperGrain: 25,
      fpsThrottle: 12,
      colorTint: 'none',
    },
  },
  {
    id: 'oil-painting',
    name: 'Impasto Oil Canvas',
    nameHi: 'ऑयल पेंटिंग कैनवस',
    category: 'art',
    description: 'Thick painterly strokes with directional edge relief and rich artistic depth.',
    descriptionHi: 'गहरे आर्टिस्टिक ब्रश स्ट्रोक्स, ऑयल पेंट टेक्सचर और रिच कलर्स।',
    accentColor: '#f59e0b',
    previewGradient: 'from-amber-600 via-orange-500 to-yellow-400',
    parameters: {
      edgeThreshold: 35,
      edgeThickness: 2,
      edgeDarkness: 50,
      colorBands: 8,
      smoothing: 9,
      saturation: 150,
      contrast: 120,
      brightness: 5,
      bloomGlow: 25,
      halftoneDotSize: 0,
      pixelBlockSize: 1,
      sketchHatch: 0,
      paperGrain: 20,
      fpsThrottle: 0,
      colorTint: 'none',
    },
  },
  {
    id: 'claymation',
    name: 'Stop-Motion Claymation',
    nameHi: 'क्लेमेशन स्टॉप-मोशन',
    category: 'retro',
    description: 'Chunky clay-like matte lighting with organic 12 FPS time quantization.',
    descriptionHi: 'क्लेमेशन लुक, मैट लाइटिंग और ऑर्गेनिक 12 फ्रेम प्रति सेकंड फील।',
    accentColor: '#ec4899',
    previewGradient: 'from-rose-500 via-pink-600 to-orange-400',
    parameters: {
      edgeThreshold: 25,
      edgeThickness: 1,
      edgeDarkness: 40,
      colorBands: 5,
      smoothing: 6,
      saturation: 120,
      contrast: 110,
      brightness: 0,
      bloomGlow: 15,
      halftoneDotSize: 0,
      pixelBlockSize: 1,
      sketchHatch: 0,
      paperGrain: 10,
      fpsThrottle: 12,
      colorTint: 'none',
    },
  },
];
